### ISSUE TITLE
Set#grep doesn't seem to work

### ISSUE THREAD

**Issue by krainboltgreene** [hamstergem/hamster#168]
``` ruby
collection
# => Hamster::Set[
#    #<Earhart::Route:0x007fd1650ca4e8 @pattern=/GET \/accounts\//, @receiver=Object>,
#    #<Earhart::Route:0x007fd1650ca218 @pattern=/GET \/accounts\/(?<id>.+)/, @receiver=Object>]

query
# => "GET /accounts/1"

collection.grep(query)
# => Hamster::Set[]

route = Earhart::Route.new(/GET \/accounts\/(?<id>.+)/, Object)
# => #<Earhart::Route:0x007fd1652968a8 @pattern=/GET \/accounts\/(?<id>.+)/, @receiver=Object>

route === "GET /accounts/1"
# => true
```

Very weird.

**Comment by krainboltgreene** [comment]
Looking deeper:

``` ruby
collection.grep(query)
# From: hamster-1.0.0/lib/hamster/set.rb @ line 199 Hamster::Set#select:
# 
#     199: def select
#     200:   return enum_for(:select) unless block_given?
#     201:   trie = @trie.select { |key, _| yield(key) }
#     202:   new_trie(trie)
#     203: end
    
return enum_for(:select) unless block_given?
# => nil

trie = @trie.select { |key, _| yield(key) }
# => #<Hamster::Trie:0x007fa200abfa28
#  @children=[],
#  @entries=
#   [nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil, nil],
#  @significant_bits=0,
#  @size=0>

new_trie(trie)
# => Hamster::Set[]

@trie
# => #<Hamster::Trie:0x007fa2003c2c98
#  @children=[],
#  @entries=
#   [nil,
#    nil,
#    nil,
#    nil,
#    nil,
#    nil,
#    nil,
#    nil,
#    nil,
#    nil,
#    nil,
#    nil,
#    nil,
#    nil,
#    nil,
#    nil,
#    nil,
#    nil,
#    nil,
#    nil,
#    [#<Earhart::Route:0x007fa2009fc078 @pattern=/GET \/accounts\/(?<id>.+)/, @receiver=Object>, nil]],
#  @significant_bits=0,
#  @size=1>
```

**Comment by krainboltgreene** [comment]
I don't think it's supposed to do that, obviously, but it makes sense now why the grep didn't work.

``` ruby
items = []
# => []
@trie = Trie.new(0)
# => #<Hamster::Trie:0x007fe42d186208 @children=[], @entries=[], @significant_bits=0, @size=0>
items.each { |item| @trie.put!(item, nil) }
# => []
@trie
# => #<Hamster::Trie:0x007fe42d186208 @children=[], @entries=[], @significant_bits=0, @size=0>
```

So it looks like this huge array with nils only happens when using `Hamster::Set::EmptySet`, which passes `[nil]` as an item to initialize.

**Comment by alexdowad** [comment]
Can you confirm whether === works with the string on the left side?

**Comment by dubek** [comment]
@krainboltgreene I think you're confusing right and left sides of `===`. Basically you have a collection of *patterns*, so an equivalent example (without Earhart) would be:

```
2.2.1 :004 > myset = Hamster::Set.new([/a/, /b/, /c/])
 => Hamster::Set[/a/, /b/, /c/] 
2.2.1 :005 > myset.grep("aaa")
 => Hamster::Set[] 
```

which is fine; same behaviour for plain Ruby arrays:

```
2.2.1 :006 > myarray = [/a/, /b/, /c/]
 => [/a/, /b/, /c/] 
2.2.1 :007 > myarray.grep("aaa")
 => [] 
```

I don't really know your application but maybe you should resort to something along the lines of:

```
chosen_route = collection.find { |route| route === query }
```

(off-topic: for an interesting implementation of an efficient HTTP request router using prefix trees see https://github.com/julienschmidt/httprouter#how-does-it-work )

**Comment by alexdowad** [comment]
That is what I was also getting at. The `nil`s you are seeing when examining the structure of the trie are also normal.

**Comment by krainboltgreene** [comment]
Really? Is there a particular reason we create big nil-filled arrays? Isn't that memory wasteful?

And I tried switching the method around:

``` ruby
def ===(query)
  query === pattern
end
```

And got the same issue.

**Comment by krainboltgreene** [comment]
Another thing I wanted to ask is: Is this even the right function for me? I realized last night that select returns an array, but what I really want is the first result found. I thought Set was lazy?

**Comment by alexdowad** [comment]
_Is there a particular reason we create big nil-filled arrays?_

Yes. First of all, remember the key characteristic of any data structure used to implement a "set": it must support a fast inclusion test. You might think that you don't often use inclusion checks on your sets, and that all you really care about is that they never contain duplicate items. But, for that "set" to efficiently filter out duplicates, it needs a fast inclusion test.

So how is a fast inclusion test possible? Linear search won't cut it, as soon as you have any significant number of items. You need some way to find the desired item within the structure more or less "directly". We do this by hashing, and using the hash code to guide our search.

For a mutable "set", a traditional hash table using either chaining or linear probing would work fine. BUT, our "sets" are immutable. That means we need a way to do fast "copies" when an item is added or removed. That can be achieved using a **hash trie**. In our case, it's a tree with 32-way branching, with searches in the tree being directed by extracting groups of 5 bits from a hash code. @harukizaemon's implementation has the unique property of storing up to 32 child nodes *and* up to 32 key-value pairs in each trie node.

How do we store those 32 items? You could use 32 instance variables, but the code would be grossly long and inefficient. Using a Ruby Array is much more reasonable.

In the example you showed, the "query" which you inserted in the set had 10100 in the 5 low-order bits of its hash code. Since the items stored in a trie node are numbered starting from zero, that meant it had to be stored as the 21st item. Now, when an object is stored into the 21st position in a Ruby Array, the lower positions have to filled with something, and that "something" is `nil`. We could use some other arbitrary object, but that wouldn't gain anything.

Most implementations of a 32-way hash trie would actually allocate a 32-element array for *every* node, regardless of whether the high-order positions were used or not. In our case, we save memory by only allocating an array of the needed size.

If we wanted to optimize for memory usage for programs which use huge numbers of very small sets, we could create one "set" class for small sets, and one for large sets. The "small set" class would pack its elements in an array and use linear search. As soon as the set got larger, it would automatically be converted to the class which uses hashing. I considered doing something like this, but decided it wasn't worth the effort.

**Comment by alexdowad** [comment]
Regarding `===`, what you actually need to try is something like this:

    "GET /accounts/1" === earhart_route

If that is false, then the behavior you are seeing from `#grep` is normal and intended. Please refer to the [documentation on Enumerable#grep](http://ruby-doc.org/core-2.1.0/Enumerable.html#method-i-grep).

**Comment by alexdowad** [comment]
`#find` is what you are looking for.

No, `Set` is not lazy. Only `List` is. Linked lists allow for a natural and efficient "lazy" implementation, but most other data structures do not. For comparison, Clojure has lazy lists which you can create using `lazy-seq`, but its other built-in structures are strict. Languages like Haskell achieve laziness not by providing a full set of "lazy" general-purpose data structures, but by delaying the evaluation of code until its results are needed.

**Comment by krainboltgreene** [comment]
That === example is what I did. I guess I still don't understand why my
code isn't working in this case, but frankly I'll want find on list anyways.

**Comment by alexdowad** [comment]
The key point to take note of is that `#grep` calls `#===` with the pattern on the *left* side. If `"GET /accounts/`" === earhart_route` is true, then the behavior you are seeing is definitely a bug. However, in that case, it would be a bug in MRI, not in Hamster, because we are using the built-in implementation of `Enumerable#grep`.

**Comment by dubek** [comment]
As a side note, in Ruby 2.x you can turn any enumerator to lazy, so:

```
myvector = Hamster::Vector.new(["aaa", "bbb", "ccc", "bb", "d"])
# => Hamster::Vector["aaa", "bbb", "ccc", "bb", "d"] 

myvector.each.lazy.select { |x| puts "WORKING ON #{x}"; x.match(/b/) }
# => #<Enumerator::Lazy: #<Enumerator::Lazy: #<Enumerator: Hamster::Vector["aaa", "bbb", "ccc", "bb", "d"]:each>>:select> 

myvector.each.lazy.select { |x| puts "WORKING ON #{x}"; x.match(/b/) }.first
WORKING ON aaa
WORKING ON bbb
# => "bbb" 
```

As opposed to normal iteration without `.lazy`:

```
myvector = Hamster::Vector.new(["aaa", "bbb", "ccc", "bb", "d"])
# => Hamster::Vector["aaa", "bbb", "ccc", "bb", "d"] 

myvector.select { |x| puts "WORKING ON #{x}"; x.match(/b/) }.first
WORKING ON aaa
WORKING ON bbb
WORKING ON ccc
WORKING ON bb
WORKING ON d
# => "bbb" 
```

I haven't investigated effects on performance.
