### ISSUE TITLE
Come up with a better namespace

### ISSUE THREAD

**Issue by nandosola** [hamstergem/hamster#171]
I don't wanna be a pedantic PITA here. I absolutely love this project, but IMHO `Hamster::List`, `Hamster::Set`, etc. don't express any particular intent and can be quite confusing, for example, during a debugging session (this actually happened to one of my SDK users). If this project is all about immutability, something like `Hamster::ImmutableCollections::*` would be much better.

**Comment by alexdowad** [comment]
Thanks for your input. I would actually like something like `Immutable::Set`, `Immutable::Vector`, and so on. `Hamster::ImmutableCollections::Set` is too long. Unfortunately, the name the project has inherited is "hamster". What would other contributors think about using `Immutable` as a namespace rather than `Hamster`? (Unfortunately, there is already an `immutable` gem. Not sure what they use for names.)

By the way, @nandosola, since you actually use this library, your input on the open PRs would be appreciated.

**Comment by krainboltgreene** [comment]
God, I'd love to have that gemname. I'm going to see if I can grab it from the author.

**Comment by alexdowad** [comment]
I've just created a fork of this gem called [immutable-ruby](https://github.com/immutable-ruby/immutable-ruby). It's unfortunate that the "immutable" gemname is taken...

Functionality is basically just like Hamster, but instead of `Hamster::Hash`, it's `Immutable::Hash`, and so on. Since there is no existing user base, I have "cleaned up" a bit by removing a few extraneous APIs. Otherwise it's just the same.

I intend to continue maintaining both `hamster` and `immutable-ruby`. Any bugs reported against one gem will be fixed in the other. However, again, since there is no installed user base for `immutable-ruby`, it is a bit freer to evolve, at least until it hits its 1.0.0 release.

@nandosola, please give it a try!
