### ISSUE TITLE
finish Hamster.from()

### ISSUE THREAD

**Issue by Bill** [hamstergem/hamster#203]
It is awful that `Hamster#from` has class name's hard coded into it. Because of that, each time we find some new class that we want to translate `from` (like `Struct` in #200) we have to change `hamster` code.

The classic way to avoid this in Ruby is to use `respond_to?` tests in place of the `Module#===` underlying `case`/`when`. That would entail coming up with the set of methods that comprise "hashiness", "arrayness", etc.

In thinking about that it's not obvious since both `Hash` and `Array` implement `[]=`. They are both "associative". Without any type information it's impossible to know that `Array#[]=` constrains the argument to quack like a whole number.

The way Clojure handles this is with interfaces. Any object that is "hashy" implements the `IPersistentMap` interface. Any object that is "arrayish" implements the `IPersistentVector` interface. If `hamster` were a Clojure library, then `Hamster.from` could ask if an object implemented `IPersistentMap` and convert it to a `Hamster::Hash` and we'd be done. Alas Ruby collections don't have such a handy way for us to determine if an object is "hashy". 

One way I have gotten around this in the past (e.g. https://github.com/Bill/enumerator-traits, https://github.com/Bill/enumerator-traits-kit) is to open a module (in the case of my example, `Enumerator`) and inject "tagging" methods into them (in my case, it was to declare (and impose) constraints like monotonicity on an `Enumerator` which then allowed me to define methods on conformant `Enumerators` that relied on monotonicity, in my case: intersection).

So I'd like to get a feel for what the maintainers think. Please choose an option:

1. `Hamster::from` is fine the way it is. Let's just edit `nested.rb` each time we run into a new situation
2. let's try and figure out the right set of methods to probe (via `respond_to?`) for each category of container kind
3. let's open `Object` or `BaseObject` and inject something like `declare_trait` and `ensure_trait` and provide a starter set of traits for Hash, Array, Struct etc. and let our users add more (outside `hamster`) as they encounter (or create!) them

If there is any interest in (3) I can come back with something more specific like maybe even a PR that adapts the ideas from https://github.com/Bill/enumerator-traits and https://github.com/Bill/enumerator-traits-kit to Hamster.

**Comment by Bill** [comment]
For (2) maybe for "hashyness" we just check `obj.respond_to(:to_h)` first and if that's truthy then we call to_h on it and convert the result to a `Hamster::Hash` otherwise we check…

The what comes next part is tricky. It feels like we'd want to check for "sorted setiness" and "setiness" next. But `SortedSet` defines no new public methods at all (it inherits from `Set`). So approach (2) can't differentiate `SortedSets` from `Sets`.

And there are other problems with (2). If we could get past `Set` and `SortedSet` I think the next thing we'd learn is that we had create a big, brittle, difficult to understand glob of code.

My early intuition is that (2) is probably a loser.

**Comment by alexdowad** [comment]
Defining extra methods on `Object` and `BasicObject` in library code is to be avoided at all costs, *unless* the purpose of the library is specifically to add those methods.

Since all Ruby code in a process shares the same `Object` class, `Array` class, `Enumerator` class, and so on, adding methods to those classes is like adding them to the global namespace. We should "tread lightly" on the global namespace; adding methods at will tends to cause incompatibilities between libraries, and the application programmer may have had their own ideas about what they wanted to do in that global namespace.

That's why we don't add helper methods to `Enumerator` unless the user specifically requests them by requiring `hamster/core_ext/enumerator`.

I can't speak for the other maintainers, but I am very open to suggestions about how better to implement `hamster/nested`. However, that "better" way should not just be "better" in stylistic purity while sacrificing things which really affect our users (like performance, etc).

I haven't found an arguably better way yet.

**Comment by xaviershay** [comment]
what @alexdowad said. I'd lean towards 1 or 2 (though as you said, maybe not much we can do there), 3 makes me nervous.

**Comment by dubek** [comment]
Since Hamster should only support converting the built-in Ruby data structures, I think 1 is OK - we should be able to cover them all, if we haven't already (up to new additions to the stdlib in the next Ruby version).

**Comment by alexdowad** [comment]
@Bill, although it looks like we may keep `hamster/nested` as it is for now, please let us know any other ideas which you have for improvement! Your opinions are valued.
