### ISSUE TITLE
Conditional puts

### ISSUE THREAD

**Issue by elben** [hamstergem/hamster#210]
It's common to build up a hash where the values are a result of different computations. Some of those computations are conditional:

``` ruby
hash = {}
hash[:abc] = some_calculation
hash[:foo] = :bar if condition1
hash[:xyz] = 123 if condition2
```

Is there a good way to do this in Hamster? I usually would do:

``` ruby
hash = Hamster.from(some_calculation)
hash = if condition1 then hash.put(:foo, :bar) else hash
hash = if condition2 then hash.put(:xyz, 123) else hash
```

My proposal is to add a `put_if`.

``` ruby
# A rough sketch on the interface
module Hamster
  class Hash
    def put_if(key, condition, &value)
      if condition
        # The value is lazily evaluated per the condition like an `if`
        v = value.call(self.get(key))
        self.put(key, v)
      else
        self
      end
    end
  end
end

Hamster.from(some_calculation)
  .put_if(:foo, condition1) { :bar }
  .put_if(:xyz, condition2) { 123 }
```

Perhaps it is a bit niche, and should be solved outside the library. In languages that have `let` (e.g. Clojure, Haskell), it's easy enough to find use temporary names for intermediate values. In Ruby, unfortunately, you'll pollute the entire method with temporary vars.

Thoughts?

**Comment by alexdowad** [comment]
Thanks for bringing up what is a very real issue with using immutable data structures in Ruby!

I think that `#put_if` is just a special case of a pattern which says: if some condition holds, get a modified copy of this immutable data, and if it doesn't, get the original. The modification could be `put`, or it could be deleting a key, filtering, mapping, etc.

**Comment by elben** [comment]
Good point on the generalized form.

Preserving the chaining-style is also difficult unless the transformation methods are in the object itself, due to how Ruby OO ties data to its interface.

In Scala, we can first build a `Seq[Option[T]]`, then convert to a `Map`, ignoring all the `None` values. This doesn't seem practical here.

If I wanted to do this with the chaining-style, but via a mechanism outside of Hamster itself, I can't think of a way to do it without building my own chainable thing. Hence why it may make sense to allow it in Hamster.

Anyways, feel free to close this—I was just pondering a better way.

**Comment by alexdowad** [comment]
Using Ruby's blocks, you could do something like:

```ruby
hash.if(condition) { |h| h.put(:foo, :bar) }
```

**Comment by alexdowad** [comment]
> feel free to close this

I don't want to close it. I would like to keep it open and hopefully get ideas from other interested parties.

I just hope we don't add more methods to the API without really making sure that it is the right decision.

**Comment by dubek** [comment]
Would the following code work for these kind of scenarios?

```ruby
hash = Hamster.from(some_calculation)
hash = hash.put(:foo, :bar) if condition1
hash = hash.put(:xyz, 123) if condition2
```

For example, if `condition1` is false, the entire assignment `hash = hash.put(:foo, :bar)` is not executed and the variable `hash` keeps its original value.

**Comment by elben** [comment]
@dubek you're right that works.

@alexdowad agreed, we shouldn't be adding new methods to the API w/o being sure of its usefulness. I think your `if` idea is interesting and would work with everything, but it feels a bit odd to basically write a backwards if statement just to get chaining. (Of course, this goes against my original idea, but hopefully this discussion sparks something useful.)

In languages where immutability is default, other data around you is immutable, so the code is structured to make transformation of immutable structures easier. In Ruby, I found it very awkward to "add" immutable data to a module full of mutation, because the structure is already very mutable.

For example, I found myself doing this a lot:

```ruby
h = Hamster::Hash.empty

... lots of mutations ...

if condition_based_off_above_mutation
  h = h.put(...)
end

.. more mutations ...

h = h.whatever
```

At this point, there is no win for using "immutable" data structures—you're now mutating the pointer!

**Comment by Bill** [comment]
Here is an ugly little start perhaps:

```ruby
class Object
 def chain_conditionally( cond, meth, *args, &block)
  if cond
    send meth, *args, &block
  else
    self
  end
end

'abc'.chain_conditionally(false, :+, 'd').chain_conditionally(true, :+, 'e')
 => "abce" 
```

With that, @elben's example could look like:

```ruby
require 'hamster'
condition1 = false
condition2 = true
Hamster.from({}).put(:abc,1).chain_conditionally(condition1, :put, :foo, :bar).chain_conditionally(condition2, :put, :xyz, 123)
 => Hamster::Hash[:xyz => 123, :abc => 1] 
```

My distaste for `chain_conditionally` as presented stems from it's object-orientedness. That gives rise to the three method parameters: `meth, *args, &block` where I might just like to take a closure. I feel like a closure would make for more readable code.

On the other hand, `chain_conditionally` is easy for most Ruby programmers to understand. It's just not all that composable, and I don't know if we've achieved improved readability versus @elben's original code. On the upside though, we eliminated the need for the (mutable) reference `hash`.

I think that if we want to go further and explore better approaches, there is gold here:

1. combinators in Ruby http://combinators.info/
2. String#to_proc for clean lambda syntax http://weblog.raganwald.com/2007/10/stringtoproc.html

It all depends on how far down the functional rabbit hole we choose to go.

Sincerely,
"No More Ruby" Bill

**Comment by alexdowad** [comment]
> At this point, there is no win for using "immutable" data structures—you're now mutating the pointer!

Mutating the pointer can still be a win in some cases. You don't have any aliasing bugs that way. Ask me how many times I have written code with aliasing bugs... (I can't count.)

Certain algorithms are easier to code correctly and efficiently when you have immutable data structures like Hamster's.

Hamster has been very deliberately designed so that our structures integrate well with code which uses the core Ruby structures. At least, that is the goal. So you don't necessarily have to convert all your Ruby code to "everything immutable, all the time".

My preference would be to use the plain old mutable Ruby structures locally (such as a temporary structure which is used within a single method and then discarded, or a structure which is passed between a few `private` methods). This is akin to the use of "transient" structures in Clojure. The benefits of immutable structures are greater for data which is accessed in many disparate places. OR, when coding an algorithm which involves backtracking, etc.

If need be, you can convert an immutable structure to mutable on method entry, hammer on it, then convert it back to immutable before returning.

Of course, if you want *all* your code to use immutable structures, all the time, that is also OK. Definitely, some of Ruby's core language syntax (for control flow, etc.) may not serve you well in that case.

It might be possible to (partially) work around the problem using some of the ideas in this thread. However, I think that Hamster really exists just to provide immutable data structures, not as a general solution to all the problems of writing pure-functional code in Ruby.

Of course, `#put_if` is a useful helper method, even if we are not trying to provide that "general solution". But I am concerned about the proliferation of `_if` methods which might ensue.

I would suggest that:

1. If you find that methods like `#put_if` really help a certain program, create a local extension for Hamster. Ruby has open classes for a reason, after all.
2. Some of these other ideas could become little libraries of their own. (Like @Bill's hamstar -- I am happy to see this kind of cross-pollination of ideas, whereby the work done here enables people to explore and innovate in new directions of their own.)
3. If you really find that `#put_if` is so compellingly useful that you keep coming back to it with every program you write, push harder to have it included in Hamster!

> "No More Ruby" Bill

I hope Hamster hasn't turned you off Ruby! Maybe there is another language which works better for your purposes?

**Comment by Bill** [comment]
>> "No More Ruby" Bill
> I hope Hamster hasn't turned you off Ruby! Maybe there is another language which works better for your purposes?

Hamster is the only thing keeping me here (for a while longer) @alexdowad.

The `chain_conditionally` I offered is ugly because it turns code like this:

`hash.put(:foo,:bar) if condition1`

Into code like this:

`hash.chain_conditionally(condition1, :put, :foo, :bar)`

How about if we had a method called `when` that would take a condition and if the condition were truthy, would return self but if it were falsy would return an object, which, no matter what message you sent it, always returned self, to wit:

```ruby

class NoOp < BasicObject
  def initialize(target); @target = target; end
  def respond_to?(sym, include_private = false)
    @target.respond_to?(sym, include_private)
  end
  def method_missing(sym, *args, &block)
    @target # no-op
  end
end

class Object
  def when( cond)
    if cond
      self
    else
      NoOp.new(self)
    end
  end
end
```

With `when` we can do this:

`Hamster.from({}).put(:abc,1).when(false).put(:foo, :bar).when(true).put(:xyz, 123)`

The `NoOp` class seems to be related to `tap`/`returning` which in turn are related to the K (Kestrel) combinators described in http://combinators.info/#kestrels.
